### ISSUE TITLE
All data described within Article in  https://tanaylab.weizmann.ac.il/metabric_rrbs are not accessible

### ISSUE THREAD

**Issue by sixone11** [tanaylab/metabric_rrbs#1]
Dear author,
I am so interested in your research "DNA methylation landscapes of 1538 breast cancers reveal a replication-linked clock, epigenomic instability and cis-regulation" published in nature communication. 
Your code is so clearly and I want to fllow your code to do some analysis, but the link in article was not accessible and I couldn't download the data.  
Like the picture below. 
![image](https://user-images.githubusercontent.com/35550239/134279090-cdb549f4-bb15-4b8c-ada3-df6a3e43a640.png)

Thank you very much in advance!
Best regards,
Vivian

**Comment by aviezerl** [comment]
Hi Vivian,

Thank you for pointing this out. We did had a problem with our server last
week. Could you please try to delete the cookies for the site and try
again? If this doesn't work, please try to access the site from another
browser.

Please tell us if it fixed the problem.

Aviezer

**Comment by sixone11** [comment]
Hi Aviezer, 

After I delete the cookies, it works.

Thank you so much for your kind help!

Vivian
