### ISSUE TITLE
Unable to download the analysis_files.tar.gz, connection is breaking multiple times

### ISSUE THREAD

**Issue by tanmayroy1979** [tanaylab/metabric_rrbs#2]
Hi

I am trying to download the data to start the analysis but everytime the connection is getting reset at around 230MB.

I have a good bandwidth connection and speed or network is not an issue.

Can you please tell me how to get the file in some other ways!

"
![image](https://user-images.githubusercontent.com/55225614/135246858-de055bae-4ae9-4c9c-b79d-27ae1984312e.png)

**Comment by aviezerl** [comment]
Hi @tanmayroy1979, 

We uploaded the data to a new AWS S3 bucket which is supposed to be more stable: 

https://metabric-rrbs.s3.eu-west-1.amazonaws.com/analysis_files.tar.gz

Please tell us if you still encounter problems. 

Aviezer

**Comment by tanmayroy1979** [comment]
Hi Aviezer

Thanks for sharing the new link. Looks like this is far better. I would ike to request you to update your main content with this new url for others also to avoide time loss.

For me this is saying to be complete in 1.5 from hours now. If i face any issue, I will update.

Thanks
Tanmay

**Comment by aviezerl** [comment]
All referrals to the old URL in this repository were changed. Please notify me if there are places I missed. 

Thanks,
Aviezer

**Comment by tanmayroy1979** [comment]
Hi Aviezer

Thanks for the update. I was able to download the material successfully.

Tanmay
