### ISSUE TITLE
scripts/init_metadata.R not exist

### ISSUE THREAD

**Issue by sixone11** [tanaylab/metabric_rrbs#3]
Hi Aviezer,

I have downloaded all data successfully and want to repeat your analysis. But maybe some key scripts are missing, for example, `scripts/init_metadata.R ` . 

If you could make these scripts public, it will help us save a lot of time to learn your study. 

Thanks in advance! 

Vivian

**Comment by aviezerl** [comment]
Indeed the file was missing, apologies! 

I added the missing file (+an updated version of init.R). Please pull the changes and try to rerun. 

Thank you for notifying us, 
Aviezer
